CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID   NUMERIC       NOT NULL,
    EMPLOYEE_NAME VARCHAR2(256) NOT NULL,
    DATE_OF_BIRTH DATE          NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID)
);

CREATE SEQUENCE EMPLOYEE_ID_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE;