INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19510102', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19520203', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19530304', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19540505', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19550605', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19560706', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19570809', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19580910', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19591011', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19601112', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19611213', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19620114', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19630215', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19640316', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19650417', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19660518', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19670619', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19680720', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19690821', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Smith', TO_DATE('19700922', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19611213', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19620114', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19630215', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19640316', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19650417', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19660518', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19670619', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19680720', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19690821', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Donovan', TO_DATE('19700922', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19611213', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19620114', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19630215', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19640316', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19650417', 'YYYYMMDD'));

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19660518', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19670619', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19680720', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19690821', 'YYYYMMDD'));
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES(EMPLOYEE_ID_SEQ.NEXTVAL, 'Johnson', TO_DATE('19700922', 'YYYYMMDD'));