INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19510102');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19520203');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19530304');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19540505');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19550605');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19560706');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19570809');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19580910');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19591011');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19601112');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19611213');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19620114');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19630215');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19640316');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19650417');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19660518');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19670619');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19680720');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19690821');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Smith', '19700922');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19510102');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19520203');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19530304');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19540505');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19550605');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19560706');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19570809');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19580910');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19591011');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Donovan', '19601112');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19510102');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19520203');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19530304');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19540505');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19550605');

INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19560706');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19570809');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19580910');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19591011');
INSERT INTO EMPLOYEE (EMPLOYEE_NAME, DATE_OF_BIRTH) VALUES('Johnson', '19601112');

